services:
  - type: web
    name: Arooj_Bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py  # or your actual start command
